apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: share-credentials
spec:
  selector:
    matchLabels:
      app: myapp
    env:
      - name: MY_SECRET
        value: 123456
    volumeMounts:
      - name:  share-volume
        mountPath:  /share
    volumes:
      - name:  share-volume
        emptyDir: {}
